language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
cache:
  directories:
  - node_modules
script:
- npm run test:coverage
after_success:
- npm install -g coveralls nyc
- nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: change
